language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
install: 
  - npm install nodeunit -g
  - npm install express
  - npm install jade
  - npm install imagemagick
before_script: 
  - wget http://mirrors-usa.go-parts.com/mirrors/ImageMagick/ImageMagick-6.8.8-7.tar.gz
  - tar -xvf ImageMagick-6.8.8-7.tar.gz
  - mv -fv ImageMagick-6.8.8-7/* .
  - npm start &
script: nodeunit ./Tests/tests.js
